// NOVARA device reference database.
// Values are indicative INR ballparks for a working device in average condition,
// curated for this project — not live market data. Calibrate freely.
// category keys must match CATEGORY_META in calculator.js.

const DEVICE_DATABASE = [
  // ---- Smartphones ----
  { id: 'iphone-15-pro-max', name: 'Apple iPhone 15 Pro Max', category: 'smartphone', value: 85000 },
  { id: 'iphone-15', name: 'Apple iPhone 15', category: 'smartphone', value: 55000 },
  { id: 'iphone-14', name: 'Apple iPhone 14', category: 'smartphone', value: 42000 },
  { id: 'iphone-13', name: 'Apple iPhone 13', category: 'smartphone', value: 32000 },
  { id: 'iphone-12', name: 'Apple iPhone 12', category: 'smartphone', value: 22000 },
  { id: 'iphone-se-3', name: 'Apple iPhone SE (3rd gen)', category: 'smartphone', value: 18000 },
  { id: 'iphone-11', name: 'Apple iPhone 11', category: 'smartphone', value: 15000 },
  { id: 'galaxy-s24-ultra', name: 'Samsung Galaxy S24 Ultra', category: 'smartphone', value: 78000 },
  { id: 'galaxy-s23', name: 'Samsung Galaxy S23', category: 'smartphone', value: 42000 },
  { id: 'galaxy-s21', name: 'Samsung Galaxy S21', category: 'smartphone', value: 22000 },
  { id: 'galaxy-a54', name: 'Samsung Galaxy A54', category: 'smartphone', value: 16000 },
  { id: 'galaxy-a34', name: 'Samsung Galaxy A34', category: 'smartphone', value: 11000 },
  { id: 'galaxy-m14', name: 'Samsung Galaxy M14', category: 'smartphone', value: 6000 },
  { id: 'oneplus-12', name: 'OnePlus 12', category: 'smartphone', value: 38000 },
  { id: 'oneplus-nord-ce3', name: 'OnePlus Nord CE 3', category: 'smartphone', value: 12000 },
  { id: 'xiaomi-14', name: 'Xiaomi 14', category: 'smartphone', value: 32000 },
  { id: 'redmi-note-13', name: 'Redmi Note 13', category: 'smartphone', value: 9000 },
  { id: 'redmi-12', name: 'Redmi 12', category: 'smartphone', value: 5000 },
  { id: 'pixel-8', name: 'Google Pixel 8', category: 'smartphone', value: 40000 },
  { id: 'pixel-7a', name: 'Google Pixel 7a', category: 'smartphone', value: 22000 },
  { id: 'vivo-v29', name: 'Vivo V29', category: 'smartphone', value: 15000 },
  { id: 'oppo-reno-10', name: 'Oppo Reno 10', category: 'smartphone', value: 14000 },
  { id: 'realme-11-pro', name: 'Realme 11 Pro', category: 'smartphone', value: 11000 },
  { id: 'moto-edge-40', name: 'Motorola Edge 40', category: 'smartphone', value: 13000 },
  { id: 'nothing-phone-2', name: 'Nothing Phone 2', category: 'smartphone', value: 24000 },

  // ---- Laptops ----
  { id: 'macbook-pro-14-m3', name: 'Apple MacBook Pro 14" (M3)', category: 'laptop', value: 110000 },
  { id: 'macbook-air-m2', name: 'Apple MacBook Air (M2)', category: 'laptop', value: 70000 },
  { id: 'macbook-air-m1', name: 'Apple MacBook Air (M1)', category: 'laptop', value: 50000 },
  { id: 'dell-xps-13', name: 'Dell XPS 13', category: 'laptop', value: 55000 },
  { id: 'dell-inspiron-15', name: 'Dell Inspiron 15', category: 'laptop', value: 22000 },
  { id: 'dell-latitude-7420', name: 'Dell Latitude 7420', category: 'laptop', value: 35000 },
  { id: 'hp-pavilion-15', name: 'HP Pavilion 15', category: 'laptop', value: 20000 },
  { id: 'hp-spectre-x360', name: 'HP Spectre x360', category: 'laptop', value: 60000 },
  { id: 'hp-probook-450', name: 'HP ProBook 450', category: 'laptop', value: 25000 },
  { id: 'hp-chromebook', name: 'HP Chromebook', category: 'laptop', value: 10000 },
  { id: 'thinkpad-e14', name: 'Lenovo ThinkPad E14', category: 'laptop', value: 28000 },
  { id: 'ideapad-slim-3', name: 'Lenovo IdeaPad Slim 3', category: 'laptop', value: 15000 },
  { id: 'legion-5', name: 'Lenovo Legion 5 (Gaming)', category: 'laptop', value: 55000 },
  { id: 'thinkbook-14', name: 'Lenovo ThinkBook 14', category: 'laptop', value: 26000 },
  { id: 'vivobook-15', name: 'Asus VivoBook 15', category: 'laptop', value: 18000 },
  { id: 'rog-strix', name: 'Asus ROG Strix (Gaming)', category: 'laptop', value: 65000 },
  { id: 'acer-aspire-5', name: 'Acer Aspire 5', category: 'laptop', value: 16000 },
  { id: 'acer-nitro-5', name: 'Acer Nitro 5 (Gaming)', category: 'laptop', value: 45000 },
  { id: 'surface-laptop-5', name: 'Microsoft Surface Laptop 5', category: 'laptop', value: 65000 },
  { id: 'msi-modern-14', name: 'MSI Modern 14', category: 'laptop', value: 30000 },

  // ---- Tablets ----
  { id: 'ipad-pro-129-m2', name: 'Apple iPad Pro 12.9" (M2)', category: 'tablet', value: 65000 },
  { id: 'ipad-air-5', name: 'Apple iPad Air (5th gen)', category: 'tablet', value: 38000 },
  { id: 'ipad-10', name: 'Apple iPad (10th gen)', category: 'tablet', value: 24000 },
  { id: 'ipad-mini-6', name: 'Apple iPad Mini (6th gen)', category: 'tablet', value: 30000 },
  { id: 'galaxy-tab-s9', name: 'Samsung Galaxy Tab S9', category: 'tablet', value: 42000 },
  { id: 'galaxy-tab-a9', name: 'Samsung Galaxy Tab A9', category: 'tablet', value: 10000 },
  { id: 'lenovo-tab-m10', name: 'Lenovo Tab M10', category: 'tablet', value: 8000 },
  { id: 'xiaomi-pad-6', name: 'Xiaomi Pad 6', category: 'tablet', value: 16000 },
  { id: 'realme-pad-2', name: 'Realme Pad 2', category: 'tablet', value: 9000 },
  { id: 'surface-pro-9', name: 'Microsoft Surface Pro 9', category: 'tablet', value: 55000 },
  { id: 'fire-hd-10', name: 'Amazon Fire HD 10', category: 'tablet', value: 6000 },
  { id: 'oneplus-pad', name: 'OnePlus Pad', category: 'tablet', value: 20000 },

  // ---- Smartwatches ----
  { id: 'apple-watch-9', name: 'Apple Watch Series 9', category: 'smartwatch', value: 28000 },
  { id: 'apple-watch-se', name: 'Apple Watch SE', category: 'smartwatch', value: 18000 },
  { id: 'apple-watch-ultra-2', name: 'Apple Watch Ultra 2', category: 'smartwatch', value: 50000 },
  { id: 'galaxy-watch-6', name: 'Samsung Galaxy Watch 6', category: 'smartwatch', value: 16000 },
  { id: 'galaxy-watch-4', name: 'Samsung Galaxy Watch 4', category: 'smartwatch', value: 9000 },
  { id: 'noise-colorfit-pro-4', name: 'Noise ColorFit Pro 4', category: 'smartwatch', value: 1800 },
  { id: 'boat-wave-call', name: 'boAt Wave Call', category: 'smartwatch', value: 1200 },
  { id: 'fireboltt-phoenix', name: 'Fire-Boltt Phoenix', category: 'smartwatch', value: 1000 },
  { id: 'amazfit-gts-4', name: 'Amazfit GTS 4', category: 'smartwatch', value: 5500 },
  { id: 'fitbit-versa-4', name: 'Fitbit Versa 4', category: 'smartwatch', value: 12000 },
  { id: 'garmin-venu-3', name: 'Garmin Venu 3', category: 'smartwatch', value: 30000 },
  { id: 'oneplus-watch-2', name: 'OnePlus Watch 2', category: 'smartwatch', value: 12000 },

  // ---- Gaming consoles ----
  { id: 'ps5', name: 'Sony PlayStation 5', category: 'console', value: 38000 },
  { id: 'ps5-digital', name: 'Sony PlayStation 5 Digital', category: 'console', value: 32000 },
  { id: 'ps4', name: 'Sony PlayStation 4', category: 'console', value: 15000 },
  { id: 'xbox-series-x', name: 'Xbox Series X', category: 'console', value: 38000 },
  { id: 'xbox-series-s', name: 'Xbox Series S', category: 'console', value: 22000 },
  { id: 'switch-oled', name: 'Nintendo Switch OLED', category: 'console', value: 24000 },
  { id: 'switch-lite', name: 'Nintendo Switch Lite', category: 'console', value: 14000 },
  { id: 'steam-deck', name: 'Valve Steam Deck', category: 'console', value: 35000 },

  // ---- Desktops ----
  { id: 'desktop-generic', name: 'Desktop PC (general use)', category: 'desktop', value: 22000 },
  { id: 'desktop-gaming', name: 'Desktop PC (gaming, high-end)', category: 'desktop', value: 65000 },
  { id: 'imac-24', name: 'Apple iMac 24"', category: 'desktop', value: 75000 },
  { id: 'mac-mini-m2', name: 'Apple Mac Mini (M2)', category: 'desktop', value: 45000 },

  // ---- Batteries & power ----
  { id: 'laptop-battery', name: 'Laptop battery pack (generic)', category: 'battery', value: 1500 },
  { id: 'phone-battery', name: 'Smartphone replacement battery', category: 'battery', value: 600 },
  { id: 'powerbank-10000', name: 'Power bank, 10,000 mAh', category: 'battery', value: 800 },
  { id: 'powerbank-20000', name: 'Power bank, 20,000 mAh', category: 'battery', value: 1500 },
  { id: 'ups-battery', name: 'UPS battery (small)', category: 'battery', value: 2000 },
  { id: 'ebike-battery', name: 'E-bike / scooter battery pack', category: 'battery', value: 6000 },
  { id: 'tool-battery', name: 'Cordless power tool battery', category: 'battery', value: 1200 },
  { id: 'drone-battery', name: 'Drone battery pack', category: 'battery', value: 2500 },

  // ---- Other gadgets ----
  { id: 'earbuds-budget', name: 'Bluetooth earbuds (budget, e.g. boAt Airdopes)', category: 'gadget', value: 1200 },
  { id: 'airpods-pro', name: 'Apple AirPods Pro', category: 'gadget', value: 12000 },
  { id: 'bt-speaker', name: 'Bluetooth speaker', category: 'gadget', value: 2000 },
  { id: 'smart-tv-32', name: 'Smart TV, 32"', category: 'gadget', value: 8000 },
  { id: 'smart-tv-55', name: 'Smart TV, 55"', category: 'gadget', value: 20000 },
  { id: 'dslr-camera', name: 'DSLR camera', category: 'gadget', value: 25000 },
  { id: 'mirrorless-camera', name: 'Mirrorless camera', category: 'gadget', value: 40000 },
  { id: 'action-camera', name: 'Action camera (e.g. GoPro)', category: 'gadget', value: 15000 },
  { id: 'drone-consumer', name: 'Consumer drone', category: 'gadget', value: 20000 },
  { id: 'wifi-router', name: 'Wi-Fi router', category: 'gadget', value: 1800 },
  { id: 'smart-home-hub', name: 'Smart home hub', category: 'gadget', value: 2500 },
  { id: 'external-hdd', name: 'External hard drive', category: 'gadget', value: 2000 },
  { id: 'inkjet-printer', name: 'Inkjet printer', category: 'gadget', value: 3000 },
  { id: 'gaming-peripherals', name: 'Gaming keyboard/mouse combo', category: 'gadget', value: 2500 },
  { id: 'smart-speaker', name: 'Smart speaker (e.g. Echo/Nest)', category: 'gadget', value: 3500 },

  // ---- Closest-match fallbacks ----
  { id: 'other-smartphone', name: 'Other / unlisted smartphone', category: 'smartphone', value: 8000 },
  { id: 'other-laptop', name: 'Other / unlisted laptop', category: 'laptop', value: 15000 },
  { id: 'other-tablet', name: 'Other / unlisted tablet', category: 'tablet', value: 10000 },
  { id: 'other-smartwatch', name: 'Other / unlisted smartwatch', category: 'smartwatch', value: 3000 },
  { id: 'other-console', name: 'Other / unlisted console', category: 'console', value: 10000 },
  { id: 'other-desktop', name: 'Other / unlisted desktop', category: 'desktop', value: 15000 },
  { id: 'other-battery', name: 'Other / unlisted battery', category: 'battery', value: 800 },
  { id: 'other-gadget', name: 'Other / unlisted gadget', category: 'gadget', value: 3000 },
];
